using Godot;

namespace PokerGame;

/// <summary>Builds the global flat, square-cornered theme used by every Control.</summary>
public static class UiTheme
{
    /// <summary>Drop a pixel font here (e.g. m5x7, Pixel Operator) and it is picked up automatically.</summary>
    public const string FontPath = "res://assets/fonts/pixel_font.ttf";

    /// <summary>Background art, generated by tools/generate_world_map.py.</summary>
    public const string WorldMapPath = "res://assets/sprites/world_map.png";

    public static Theme Build()
    {
        var theme = new Theme { DefaultFontSize = 10 };
        if (ResourceLoader.Exists(FontPath))
            theme.DefaultFont = GD.Load<Font>(FontPath);

        theme.SetStylebox("normal", "Button", Box(new Color("2d3a5a"), PixelArt.Paper));
        theme.SetStylebox("hover", "Button", Box(new Color("3d4f7a"), PixelArt.Gold));
        theme.SetStylebox("pressed", "Button", Box(new Color("1f2840"), PixelArt.Gold));
        theme.SetStylebox("disabled", "Button", Box(new Color("23283a"), new Color("555a6a")));
        theme.SetStylebox("focus", "Button", new StyleBoxEmpty());
        theme.SetColor("font_color", "Button", PixelArt.Paper);
        theme.SetColor("font_hover_color", "Button", PixelArt.Gold);
        theme.SetColor("font_disabled_color", "Button", new Color("6a6f80"));
        theme.SetStylebox("panel", "Panel", Box(new Color("141826e0"), new Color("4a5270")));
        theme.SetStylebox("panel", "PanelContainer", Box(new Color("141826f0"), PixelArt.Gold, 8));
        theme.SetColor("font_color", "Label", PixelArt.Paper);
        return theme;
    }

    /// <summary>
    /// Adds <paramref name="control"/> to <paramref name="parent"/>, then sets its rect.
    /// Sizing must happen after AddChild: outside the tree a Control measures itself with
    /// the engine's default 16px font, and the inflated size never shrinks back.
    /// </summary>
    public static T AddAt<T>(this Node parent, T control, Vector2 position, Vector2 size) where T : Control
    {
        parent.AddChild(control);
        control.Position = position;
        control.Size = size;
        return control;
    }

    private static StyleBoxFlat Box(Color bg, Color border, int margin = 3)
    {
        var box = new StyleBoxFlat { BgColor = bg, BorderColor = border, AntiAliasing = false };
        box.SetBorderWidthAll(1);
        box.SetContentMarginAll(margin);
        return box;
    }
}
