using Godot;

namespace PokerGame;

/// <summary>Builds the global flat, square-cornered theme used by every Control.</summary>
public static class UiTheme
{
    /// <summary>Drop a pixel font here (e.g. m5x7, Pixel Operator) and it is picked up automatically.</summary>
    public const string FontPath = "res://assets/fonts/pixel_font.ttf";

    /// <summary>Background art, generated by tools/generate_world_map.py.</summary>
    public const string WorldMapPath = "res://assets/sprites/world_map.png";

    // Where the background map is centred (Atlantic / Europe / Africa), in degrees.
    private const float MapCenterLongitude = 15;
    private const float MapCenterLatitude = 10;

    /// <summary>
    /// Fills <paramref name="size"/> with a crop of the equirectangular world map, drawn at a whole-number
    /// scale (at least 4x) so every map cell stays a crisp square block.
    /// </summary>
    public static void DrawWorldMap(CanvasItem canvas, Texture2D map, Vector2 size)
    {
        var tex = map.GetSize();
        float scale = Mathf.Max(4, Mathf.Ceil(Mathf.Max(size.X / tex.X, size.Y / tex.Y)));
        var region = size / scale;
        var center = new Vector2((MapCenterLongitude + 180) / 360 * tex.X, (90 - MapCenterLatitude) / 180 * tex.Y);
        var origin = (center - region / 2).Clamp(Vector2.Zero, tex - region).Floor();
        canvas.DrawTextureRectRegion(map, new Rect2(Vector2.Zero, region * scale), new Rect2(origin, region));
    }

    /// <summary>UI text size, and the height of one line of it (measured for the default font).</summary>
    public const int FontSize = 14;
    public const int LineHeight = 20;

    public static Theme Build()
    {
        var theme = new Theme { DefaultFontSize = FontSize };
        if (ResourceLoader.Exists(FontPath))
            theme.DefaultFont = GD.Load<Font>(FontPath);

        theme.SetStylebox("normal", "Button", Box(new Color("2d3a5a"), PixelArt.Paper));
        theme.SetStylebox("hover", "Button", Box(new Color("3d4f7a"), PixelArt.Gold));
        theme.SetStylebox("pressed", "Button", Box(new Color("1f2840"), PixelArt.Gold));
        theme.SetStylebox("disabled", "Button", Box(new Color("23283a"), new Color("555a6a")));
        theme.SetStylebox("focus", "Button", new StyleBoxEmpty());
        theme.SetColor("font_color", "Button", PixelArt.Paper);
        theme.SetColor("font_hover_color", "Button", PixelArt.Gold);
        theme.SetColor("font_disabled_color", "Button", new Color("6a6f80"));
        theme.SetStylebox("panel", "Panel", Box(new Color("141826e0"), new Color("4a5270")));
        theme.SetStylebox("panel", "PanelContainer", Box(new Color("141826f0"), PixelArt.Gold, 8));
        theme.SetColor("font_color", "Label", PixelArt.Paper);
        return theme;
    }

    /// <summary>
    /// Adds <paramref name="control"/> to <paramref name="parent"/>, then sets its rect.
    /// Sizing must happen after AddChild: outside the tree a Control measures itself with
    /// the engine's default 16px font, and the inflated size never shrinks back.
    /// </summary>
    public static T AddAt<T>(this Node parent, T control, Vector2 position, Vector2 size) where T : Control
    {
        parent.AddChild(control);
        control.Position = position;
        control.Size = size;
        return control;
    }

    private static StyleBoxFlat Box(Color bg, Color border, int margin = 3)
    {
        var box = new StyleBoxFlat { BgColor = bg, BorderColor = border, AntiAliasing = false };
        box.SetBorderWidthAll(1);
        box.SetContentMarginAll(margin);
        return box;
    }
}
